### PR TITLE
Puppycam by FazanaJ - analog camera port for vita

### PR DESCRIPTION
**Pull request by ghost**
A quick port of the patch. Everything seems to be working fine. 
Edit: there is a bug with the config file saved by puppycam, gonna look into it later.

### CODE REVIEW

**Comment by bythos14** [comment]
I've figured out the config issue, pushed a fix to the master branch. Also fixed a crash when loading saves and fixed the indentation in controller_vita.c. You can find those adjustments here https://github.com/bythos14/sm64-vita/commit/0813cdbaadd3b5fd0c08c8d988984eeed1484f8e. Lmk what you think

**Comment by ghost** [comment]
Oh my, thank you! I found the config bug, but the crash was sending me nuts.

> I've figured out the config issue, pushed a fix to the master branch. Also fixed a crash when loading saves. Also fixed the indentation in controller_vita.c. You can find those adjustments here [0813cdb](https://github.com/bythos14/sm64-vita/commit/0813cdbaadd3b5fd0c08c8d988984eeed1484f8e). Lmk what you think

**Comment by bythos14** [comment]
Merged: https://github.com/bythos14/sm64-vita/commit/cad8b7ea654e240322b95dac8446aa91f47614a7

Thanks

**Comment by MajorTom87** [comment]
does it work without problems then?

**Pull request closed without merging**
